name: WebDriverIO Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        browser: [chrome, firefox]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run WebDriverIO tests
      run: npx wdio run wdio.conf.js

    - name: Generate Allure report (optional)
      if: always()
      run: |
        npx allure generate allure-results --clean

    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: allure-results/

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: artifacts/screenshots/
