name: WebDriverIO Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # WebDriverIO поддерживает Node.js 16

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install WebDriverIO CLI
      run: npm install --save-dev @wdio/cli

    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        npm install chromedriver

    - name: Run WebDriverIO tests
      run: npx wdio run wdio.conf.js

    - name: Generate Allure report (optional)
      if: success()
      run: |
        npx allure generate allure-results --clean
        npx allure open
